# -*- coding: utf-8 -*-
"""FINAL_Abalone3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1IF1VsNfOn8tRxgHkwbS_lShu_hcThC8s
"""

#!pip install -q streamlit

import plotly.express as px
#!pip install plotly --upgrade

import PIL
from PIL import Image

import streamlit as st

title = st.text_input('CODEOP Data Sciense Course','ABALONE: Choossing Project / EDA / Machine Learning / Dashboarding')
st.write('versió 1')

# mostrar barra lateral
st.sidebar.header("Presentat per:")
st.sidebar.text("Victòria Oset ")
st.sidebar.text("   ")
st.sidebar.header("Elements treballats en aquest projecte:")
st.sidebar.text("Dashboard: STREAMLIT")
st.sidebar.text("Representació gràfica de dades:")
st.sidebar.text("MATPLOT, PLOTY, SEABORN, PIL")
st.sidebar.text("Edició: COLAB, VISUAL STUDIO CODE")
st.sidebar.text("CODI: PYTHON, NUMPY, PANDAS, RANDOM")

st.title("Salvem el Abalone?")

checkbox_one = st.checkbox("Yes")
checkbox_two = st.checkbox("No")

if checkbox_one:
    value = "Yes, som-m'hi!!!!"
elif checkbox_two:
    value = "No, WTF???"
else:
    value = "Què em dius?"

st.write(f"You selected: {value}")

st.title("APARTAT 1: Objectiu")

"""En aquest notebook realitzarem una anàlisi exploratori de dades (EDA/AED) sobre el conjunt de dades del Abalone, que es pot trobar a https://archive.ics.uci.edu/ml/datasets/Abalone. 


Les temperatures del mars han sigut obtingudes de la web https://rwu.pressbooks.pub/webboceanography/chapter/6-2-temperature/.



Partim del suposit que treballem al centre de Recerca Biomarina DeepSea i que tenim una partida económica per investigar el cicle de vida del Abalone, les seves migracions, edat de procreació i decadència.

També volem veure com l'Abalone es veuria afectat amb el pas del temps, uns 10 anys i una pujada de temperatures dels oceans de 2 graus. 


L'anàlisi es divideix en cinc apartats: 

- **A l'apartat 1** presentem breument què és un Abalone i el perquè d'aquesta investigació.
- **A la secció 2** neteja i revisió del conjunt d'atributs del Abalone.
- **A l'apartat 3** realitzem l'anàlisi atributs. 
- **A la secció 4** busquem correlacions entre els atributs i fem els càlculs per veure com afectaria el canvi climatic.

- **Conclusions:** Finalment a la secció 5 presentem les nostres conclusions.

"""

st.title("APARTAT 1: Presentació Abalone")

#image = Image.open('/content/Abalone3.jpg')

image = Image.open('Abalone3.jpg')

st.image(image, caption="Vista dels Rings d'un Abalone")

"""Investigacions recents centrades en l'espècie marina anomenada Abalon ( Els Haliotids (Haliotidae) de la família dels mol·luscs gasteròpodes, molt estimats per la seva carn) ens indiquen que estan en perill d'extinció imminent.

[Anem a veure de que parlem...](https://www.elcorteingles.es/gourmet-club-shop/0110113321200308-club-del-gourmet-abalone-in-olive-oil-tin-63-drained-weight-g/#)

Amb l'objectiu d'investigar com afecta el canvi climatic i la pujada de temperatures dels mars, neix aquest projecte de Data Scientist.


"""

st.title("APARTAT 2. Dades d'estudi")

"""Treballarem amb les dades obtingudes sobre la situació actual del Abalones i que tenim en format net .CSV"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import random

import plotly.express as px
import plotly.graph_objects as go
import matplotlib.pyplot as plt
import seaborn as sns

from pandas.api.types import is_numeric_dtype

import warnings

warnings.filterwarnings('ignore')

sns.set()

# %matplotlib inline

#abalone = pd.read_csv('/content/abalone31.csv', sep=';')
abalone = pd.read_csv('abalone31.csv', sep=';')
#abalone.head()

show_desc= abalone.describe()
st.table(show_desc)

#abalone.describe()

#print(abalone)
#Tenim les nostres dades sense NULLS.

"""Comprovem que tenim les dades llestes per treballar amb elles:"""

show_nan=abalone.isna().sum()

st.table(show_nan)

st.title("APARTAT 3. EDA")

st.header("3.1. L'atribut objectiu Rings")

"""L'anàlisi mostra que els valors de l'atribut Ring oscil·len entre 1 i 29 anells en un exemplar d'Abalone. No obstant això, els valors més freqüents dels anells es concentren molt al voltant de la mediana de la distribució. Observem que és possible aproximar la distribució d'aquest atribut a una corba normal."""

rows = 2
cols = 2
i = 0

fig1= plt.figure(figsize=(cols * 5, rows * 5))

i += 1
plt.subplot(rows, cols, i)
plt.xticks(range(0, 31, 4))
plt.xlim(0, 30)
num_rings = sns.distplot(abalone['Rings'], kde=False, bins=range(0, 31, 2))

i += 1
plt.subplot(rows, cols, i)
num_rings = sns.distplot(abalone['Rings'])

st.write(fig1)

st.header("3.2 Atributs de mida")

"""En aquest apartat, analitzem els atributs que representen les dimensions del Abalone. Aquests atributs són Longitud, Diàmetre i Alçada.

Creem un histograma de densitat.
Un cop més, observem una distribució normal.
"""

abalone = abalone[abalone['Height'] < 0.4]

fig2= plt.figure(figsize=(15, 15))

colors = sns.color_palette()

lines = 3
rows = 3
i = 0

i += 1
plt.subplot(lines, rows, i)
_ = sns.distplot(abalone['Length'], color=colors[i % 3])
    
i += 1
plt.subplot(lines, rows, i)
_ = sns.distplot(abalone['Diameter'], color=colors[i % 3])

i += 1
plt.subplot(lines, rows, i)
_ = sns.distplot(abalone['Height'], color=colors[i % 3])


st.write(fig2)

st.header("3.3. Atributs de pes")

"""Fem igual amb els atributs de pes. Es van observar distribucions similars, però, per als atributs de pes, la corba de campana és una mica més gran."""

abalone = abalone[abalone['Whole weight'] < 0.5]
fig3= plt.figure(figsize=(20, 15))

colors = sns.color_palette()

rows = 3
cols = 4
i = 0

i += 1
plt.subplot(rows, cols, i)
_ = sns.distplot(abalone['Whole weight'], color=colors[i % cols])
    
i += 1
plt.subplot(rows, cols, i)
_ = sns.distplot(abalone['Shucked weight'], color=colors[i % cols])

i += 1
plt.subplot(rows, cols, i)
_ = sns.distplot(abalone['Viscera weight'], color=colors[i % cols])


st.write(fig3)

st.header("3.4. Sexe")

"""L'atribut Sexe és una variable categòrica. Els valors possibles són: M per a Mascle, F per a Femella i I de Infant (un Abalone encara no adult).

Em analitzat el recompte de cada categoria amb un diagrama de porcions i podem concloure que, el conjunt de dades està equilibrat.
"""

df = abalone

df.groupby("Sex").count()

#OK

labels = ['Male', 'Female', 'Infant']
sizes = [1528,1307,1342]
 
explode = (0, 0, 0.1)  

fig41, ax1 = plt.subplots()
ax1.pie(sizes, explode=explode, labels=labels, autopct='%1.1f%%',
        shadow=True, startangle=90)
ax1.axis('equal')  
fig41.set_figheight(5)
fig41.set_figwidth(5)
st.pyplot(fig41)

st.header("3.5 Ubicació i migració")

#image2 = Image.open('/content/SeasMap.jpg')

image2 = Image.open('SeasMap.jpg')

st.image(image2, caption='Mapa dels Mars')

"""Segons les dades obtingudes, podem determinar que trobem els Abalones de menors Rings, infants amb menys de 10 Rings en aigues fredes mentres que poc a poc, va migrant en edat adulta a aigues més calentes."""

# OK Comprovo el GroupBy per anar pensant com fer la grafica de localització dels Abalons entre els diferents mars.
# no arribem a veure els Abalone del mar Carib perque estan agregats en Sea > Sex.


rings_gk = abalone.groupby(['Sea','Sex'])

#rings_gk.first()

show_rings_gk= rings_gk.first()

st.dataframe(show_rings_gk)

# Genero una funció per tal d'agrupar per "Sea" cada Abalone segons el 'count' total per Rings' que equivaldria a l'edat

def generate_rating_df(abalone):
    rating_df = abalone.groupby(['Sea', 'Rings']).agg({'Sex': 'count'}).reset_index()
    rating_df.columns = ['Sea', 'Rings', 'counts']
    rating_df = rating_df.sort_values('Rings')
    return rating_df

# Fem el grafic de barres per representar edat del Abalon i el "Sea" on els trobem.

rating_df = generate_rating_df(abalone)

fig5=px.bar(rating_df, x='Sea', y='counts', color ='Rings')
#fig.show()

st.write(fig5)

#print(rating_df)

st.header("3.6 A quines temperatures crien els Abalons?")

"""Podem comprovar amb aquesta gràfica el que ja coneixem.

1. Els Abalons desoven en aigües fredes entre 11 i 14 graus aproximadamente on els ous seran fecundats on trobem el gruix del Infants (South Atlantic/South Pacific). 

2. Es mouran una mica fins aigües pel més calides de entre 15 i 20 graus al ser adults. 

3. Finalment, a la seva vellesa, aniran cap a unes aigües més càlides en una llarga migració fins al Mar Carib.
"""

temperature_df = abalone.groupby(['Rings','Temperature']).agg({'Sex': 'count'}).reset_index()
#rings_df = abalone.groupby(['Rings']).agg({'Sex': 'count'}).reset_index()


fig6 = px.scatter(temperature_df, x="Rings", y="Temperature", trendline="ols")
#fig.show()

st.write(fig6)

st.title("APARTAT 4. Anàlisi multivariant")

st.header("4.1 Observació de correlacions: Mapa de calor")

"""Per veure com es relacionen els atributs del conjunt de dades i com influeixen les variables independents en la variable objectiu em creat un mapa de calor:"""

fig7= plt.figure(figsize=(10, 10))
corr = abalone.corr()
_ = sns.heatmap(corr, annot=True)

st.write(fig7)

"""Analitzant la matriu de correlació, observem que la temperatura dels mars té una gran influencia. Juntament amb el diametre serien les dades que més es correlacionen amb els Rings. """

#fig8, axes = plt.subplots(2,1)

fig81 = sns.jointplot(data=abalone, x='Rings', y='Diameter', kind='reg')
fig91 = sns.jointplot(data=abalone, x='Rings', y='Temperature', kind='reg')

st.pyplot(fig81)
st.pyplot(fig91)

st.header("4.1. Com varia la correlació amb el nombre de Rings?")

"""A partir de l'anàlisi anterior, decidim investigar la variació de la correlació pel que fa al nombre d'anells amb més detall. Hem provat molts valors i hem trobat que la regió delimitada per Rings < 10 té una major correlació entre els atributs independents i la variable objectiu.

Finalment, analitzem com influeixen les categories en les correlacions Rings x Temperatura i Rings x Sex.

Com que els abalons infantils tenen valors més baixos de Rings, la conseqüència es que la temperatura té una correlació més forta. 

Observant la corba de regressió de la categoria Infantil, observem que la seva inclinació és més propera als 45°.
"""

fig141= plt.figure(figsize=(20, 5))

fig14= sns.lmplot(data=abalone, x='Rings', y='Temperature', hue='Sex', fit_reg=True)

st.pyplot(fig14)

st.header("4.3 Càlculs i previsió del Canvi Climatic")

"""A continuació, farem la projecció de les dades per tal de veure com afectaria una pujada de la temperatura de l'aigua del mar d'uns 2 graus.

Recordem que els Abalons neixen en aigues fredes on permaneixen fins edad adulta per tal de procrear. Finalment, els abalons migran cap a aigues més calentes on moren.

"""

image = Image.open('SeaTemp.jpg')

st.image(image, caption="Mapa de temperatures, font de 2021")

"""En aquesta gràfica veiem en vermell com la pujada de temperatures acaba amb la població Infantil i la nova linea de tendecia ens indica que l'espècie s'estanca abans de desapareixer.

En verd podem veure que alguns Abalone arribarien al l'edat adulta de 10 Rings pero al pujar les temperatures després, moririen abans d'arribar a la vellesa, el 29 Rings.

Per fer aquesta gàfica, hem utilitzat random.gauss.
"""

abalone['Temp_10'] = abalone['Temperature'] + random.gauss(2, 0.25)
abalone['Supervivents'] = (abalone['Temperature'] > abalone['Temp_10'].min()) & (abalone['Temp_10'] < abalone['Temperature'].max())

color_discrete_map = {'Supervivents': 'Red'}
fig15 = px.scatter(abalone, x="Rings", y="Temp_10", trendline="ols", color='Supervivents', color_discrete_map=color_discrete_map)
                                      
st.write(fig15)

st.header("APARTAT 5. Conclusió")

"""En observar la correlació entre l'atribut objectiu Rings i les variables independents, arribem a la conclusió que és possible construir un model per predir el valor objectiu en funció dels atributs independents.

El pes dels abalons varia proporcionalment a les seves mides.

No hi ha diferències significatives en la mida, el pes i el nombre de rings entre els abalons mascles/femelles

Els grups d'Abalons Infantils presenten valors mitjans més baixos de mida, pes i nombre de rings com és d'esperar.

El pes i l'alçada dels abalons varia segons l'edat fins a l'edat adulta que podem dir que seria 11,5 anys (10 rings), després que la mida i el pes de la vida adulta deixin de variar, i després de 16,5 anys (15 rings) aquestes mesures no estan correlacionades.

Amb la previsió de l'espècie feta per d'aquí a 10 anys i una pujada de les temperatures del mar de 2 graus, podem veure una caiguda dràstica en el número de Infants de Abalone i progressivament, també en edad adulta.
"""